blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
edition = "2018"
empty_item_single_line = true
enum_discrim_align_threshold = 25
fn_args_layout = "Tall"
force_explicit_abi = true
force_multiline_blocks = false
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = false
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_block_trailing_comma = true
max_width = 120
merge_derives = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 25
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
version = "Two"
where_single_line = false
